spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:9000/realms/ventionteams/protocol/openid-connect/token/introspect
          client-id: ventionteams-openid
          client-secret: 79sfub70V4RHlIHXsXCiZrPA5lEqQdw2