spring:
  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: http://localhost:9000/oauth2/introspect
          client-id: introspector-id
          client-secret: Dl6aFw44COthtGiWiSlARD0V1iRkshmC