server:
  port: 8090
app:
  value: 1
spring:
  application:
    name: ResourceApp
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/