spring:
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:9000
        registration:
          gateway-user:
            provider: spring
            client-name: get health
            client-id: user-openid
            client-secret: Dl6aFw44COthtGiWiSlARD0V1iRkshmA
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - read
          gateway-admin:
            provider: spring
            client-name: get token info
            client-id: admin-openid
            client-secret: Dl6aFw44COthtGiWiSlARD0V1iRkshmB
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - token